---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-app2
spec:
  destinations:
  - server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/iocanel/my-app2.git
